### ISSUE TITLE
missing files from npm

### ISSUE THREAD

**Issue by Jazcash** [auswuchs/vue-dialog#1]
Stumbled on this by googling "usePrompt" and "useDialog" looking for something that does exactly this for Vue 3. Tried using it, but seems not all the things are correctly published to npm?

![image](https://user-images.githubusercontent.com/1434248/233813952-454af686-2ec7-43b3-be4a-06170f5960f7.png)

Missing the main composable as well as typings and css

**Comment by auswuchs** [comment]
> Stumbled on this by googling "usePrompt" and "useDialog" looking for something that does exactly this for Vue 3. Tried using it, but seems not all the things are correctly published to npm?
> 
> ![image](https://user-images.githubusercontent.com/1434248/233813952-454af686-2ec7-43b3-be4a-06170f5960f7.png)
> 
> Missing the main composable as well as typings and css


Sorry, the package wasn't published at all, it was only on GH. 
Note the changes in the readme, since the `vue-dialog` name was already taken, I changed the name of the package
